# migration-guard-test-app - Orchestrator Makefile
# Generated by ke-rails

.DEFAULT_GOAL := help
SHELL := /bin/bash

# Load environment variables
-include .env
export

# Include all sub-makefiles
-include makefiles/*.mk

# Colors for output
YELLOW := \033[1;33m
GREEN := \033[1;32m
RED := \033[1;31m
NC := \033[0m # No Color

#=============================================================================
# Primary Commands
#=============================================================================

.PHONY: setup
setup: ## Initial setup of the development environment
	@echo -e "$(GREEN)🚀 Setting up migration-guard-test-app...$(NC)"
	@make docker-build
	@make bundle-install
	@make db-setup
	@echo -e "$(GREEN)✅ Setup complete! Run 'make start' to begin.$(NC)"

.PHONY: start
start: ## Start all services
	@echo -e "$(GREEN)Starting services...$(NC)"
	@docker-compose up -d
	@echo -e "$(GREEN)🌐 Application running at http://localhost:3000$(NC)"
	@echo -e "$(YELLOW)View logs with: make logs$(NC)"

.PHONY: stop
stop: ## Stop all services
	@docker-compose stop

.PHONY: restart
restart: stop start ## Restart all services

.PHONY: reset
reset: ## Reset to clean state (with confirmation)
	@echo -e "$(RED)⚠️  This will delete all data and rebuild from scratch!$(NC)"
	@read -p "Are you sure? [y/N] " -n 1 -r; \
	echo; \
	if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
		make clean; \
		make setup; \
	fi

#=============================================================================
# Development Workflow
#=============================================================================

.PHONY: dev
dev: ## Start with live logs
	@docker-compose up

.PHONY: console
console: ## Rails console
	@docker-compose run --rm web bin/rails console

.PHONY: bash
bash: ## Bash shell in web container
	@docker-compose run --rm web bash

.PHONY: logs
logs: ## View logs (use SERVICE=name for specific service)
	@docker-compose logs -f $${SERVICE:-}

#=============================================================================
# Database Commands
#=============================================================================

.PHONY: db-console
db-console: ## Database console
	@docker-compose run --rm web bin/rails dbconsole

.PHONY: db-migrate
db-migrate: ## Run database migrations
	@docker-compose run --rm web bin/rails db:migrate

.PHONY: db-rollback
db-rollback: ## Rollback last migration
	@docker-compose run --rm web bin/rails db:rollback

.PHONY: db-seed
db-seed: ## Seed the database
	@docker-compose run --rm web bin/rails db:seed

#=============================================================================
# Testing & Quality
#=============================================================================

.PHONY: test
test: ## Run all tests and checks
	@echo -e "$(YELLOW)Running all tests and checks...$(NC)"
	@make test-rspec
	@make test-rubocop
	@echo -e "$(GREEN)✅ All tests passed!$(NC)"

.PHONY: test-watch
test-watch: ## Run tests in watch mode
	@docker-compose run --rm web bundle exec guard

.PHONY: pre-commit
pre-commit: ## Run pre-commit checks
	@make test-rubocop-changed
	@make test-rspec-changed
	@echo -e "$(GREEN)✅ Ready to commit!$(NC)"

#=============================================================================
# Deployment
#=============================================================================

.PHONY: deploy-staging
deploy-staging: ## Deploy to staging environment
	@echo -e "$(YELLOW)Deploying to staging...$(NC)"
	@make test
	@make docker-build-prod
	@make docker-push TAG=staging-$$(git rev-parse --short HEAD)
	@make nomad-deploy ENV=staging
	@echo -e "$(GREEN)✅ Deployed to staging!$(NC)"

.PHONY: deploy-production
deploy-production: ## Deploy to production environment
	@echo -e "$(RED)🚀 Deploying to PRODUCTION$(NC)"
	@make test
	@read -p "Ready to deploy to production? [y/N] " -n 1 -r; \
	echo; \
	if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
		make terraform-plan ENV=production; \
		read -p "Apply Terraform changes? [y/N] " -n 1 -r; \
		echo; \
		if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
			make terraform-apply ENV=production; \
			make docker-build-prod; \
			make docker-push TAG=production-$$(git rev-parse --short HEAD); \
			make nomad-deploy ENV=production; \
			echo -e "$(GREEN)✅ Successfully deployed to production!$(NC)"; \
		fi; \
	fi

#=============================================================================
# Utilities
#=============================================================================

.PHONY: clean
clean: ## Remove containers, volumes, and temp files
	@docker-compose down -v --remove-orphans
	@rm -rf tmp/* log/*
	@echo -e "$(GREEN)✅ Clean complete$(NC)"

.PHONY: update
update: ## Update dependencies and rebuild
	@echo -e "$(YELLOW)Updating dependencies...$(NC)"
	@docker-compose run --rm web bundle update
	@make docker-build
	@echo -e "$(GREEN)✅ Update complete$(NC)"

#=============================================================================
# Help
#=============================================================================

.PHONY: help
help: ## Show this help message
	@echo -e "$(GREEN)migration-guard-test-app - Available Commands$(NC)"
	@echo
	@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "$(YELLOW)%-20s$(NC) %s\n", $$1, $$2}' | \
		sort
	@echo
	@echo "For more information, visit: https://github.com/kalkomey/migration-guard-test-app"
