# syntax=docker/dockerfile:1
FROM ruby:3.4.5-slim AS base

# Install base dependencies
RUN apt-get update -qq &&     apt-get install -y --no-install-recommends       build-essential       curl       libpq-dev postgresql-client       nodejs       libvips &&     rm -rf /var/lib/apt/lists/*


# Set production environment
ENV RAILS_ENV=production
ENV BUNDLE_WITHOUT=development:test
ENV BUNDLE_DEPLOYMENT=true
ENV RAILS_LOG_TO_STDOUT=true
ENV RAILS_SERVE_STATIC_FILES=true

# Create app directory
WORKDIR /app

# Install bundler
RUN gem install bundler -v '~> 2.4'
